
using SandBox.GauntletUI.AutoGenerated1;
using Diplomacy.Religions;

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading;

using TaleWorlds.CampaignSystem;
using TaleWorlds.CampaignSystem.Extensions;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.Core.ViewModelCollection.ImageIdentifiers;
using TaleWorlds.Library;
using TaleWorlds.LinQuick;
using TaleWorlds.MountAndBlade.View;
using TaleWorlds.ObjectSystem;

using static System.Net.Mime.MediaTypeNames;
using static TaleWorlds.CampaignSystem.CampaignBehaviors.LordConversationsCampaignBehavior;
using static TaleWorlds.Core.Equipment;
using Diplomacy.Extensions;
using Diplomacy.GauntletInterfaces;

namespace Diplomacy.Religions.ViewModel;

public class SettlementReligionVM : FilterableViewModel
{

    //public MBBindingList<EquipmentCardVM> Cards;
    private readonly Action _onComplete;
    public MBBindingList<SettlementReligionSectionVM> Rows { get; set; } = new MBBindingList<SettlementReligionSectionVM>();
    private SettlementReligionContainer _settlementReligion;

    public SettlementReligionVM(Settlement settlement, Action onComplete)
    {
        _onComplete = onComplete;
        _settlementReligion = settlement.GetSettlementReligionContainer();
        RefreshDataView();
    }

    public void SettlementReligionSortPopup()
    {
        /*List<InquiryElement> list = new List<InquiryElement>();
        foreach (string sortItem in _sortOptions)
        {
            list.Add(new InquiryElement(sortItem, sortItem, null));
        }
        string newSortByText = "";
        MBInformationManager.ShowMultiSelectionInquiry(new MultiSelectionInquiryData("Filter by options:", "", list, isExitShown: true, 1, 1, "Continue", null, delegate (List<InquiryElement> args)
        {
            if (args == null || args.Any())
            {
                InformationManager.HideInquiry();
                IEnumerable<string> enumerable = args.Select((InquiryElement element) => element.Identifier as string);

                foreach (string item in enumerable)
                {
                    newSortByText = item;
                    break;
                }
                if (newSortByText != _sortByText)
                {
                    SortByText = newSortByText;
                    this.Rows.Clear();
                    this.RefreshDataView();
                }
            }
        }, null));*/

    }


    private bool isFilterEnabled()
    {
        /*var flag1 = (base.FilterTiers.Count > 0);
        var flag2 = (base.FilterCulture.Count > 0);
        var flag3 = (base.FilterWeaponTypes.Count > 0);
        var flag4 = (_filter_armour_types.Count > 0);
        bool filterEnabled = (flag1 || flag2 || flag3 || flag4);




        if (filterEnabled)
        {
            CultureFilter = string.Join(",", base.FilterCulture);
            if (_equipmentType.StartsWith("Wep"))
                EquipmentFilter = string.Join(",", base.FilterWeaponTypes);
            else
                EquipmentFilter = string.Join(",", _filter_armour_types);
            TierFilter = string.Join(",", base.FilterTiers);
        }
        return filterEnabled;*/
        return true;
    }

    public List<ItemObject> GetSortedList(List<ItemObject> currentList)
    {
        List<ItemObject> localList = currentList;

        /*Func<ItemObject, object> keySelector;
        Func<ItemObject, bool> filterNull;

        if (!string.IsNullOrEmpty(_sortByText) && _sortByText != "Default")
        {
            filterNull = p =>
            {
                return true;
            };

            keySelector = p =>
            {
                var propInfo = p.GetType().GetProperty(_sortByText).ToString();
                if (propInfo == null) return null; // Handle property not found
                return propInfo;
            };
            if ((_sortByText == "Name"))
            {
                keySelector = p =>
                {
                    return p.Name.ToString();
                };
            }
            if (_sortByText == "Weight" || _sortByText == "Tier")
            {
                //Different values based on the itemType
                keySelector = p =>
                {
                    var propInfo = p.GetType().GetProperty(_sortByText);
                    if (propInfo == null) return null; // Handle property not found
                    return propInfo.GetValue(p);
                };

                filterNull = p =>
                {
                    var propInfo = p.GetType().GetProperty(_sortByText);
                    return (propInfo.GetValue(p) != null);
                };

            }
            else if (_equipmentType.StartsWith("Wep"))
            {


                keySelector = p =>
                {
                    var weapon = p.Weapons.FirstOrDefault(); // Use FirstOrDefault for safety
                    if (weapon == null) return null; // Handle null weapon gracefully

                    var propInfo = weapon.GetType().GetProperty(_sortByText);
                    if (propInfo == null) return null; // Handle property not found



                    return propInfo.GetValue(weapon);
                };

                filterNull = p =>
                {
                    var weapon = p.Weapons.FirstOrDefault(); // Use FirstOrDefault for safety
                    if (weapon == null) return false; // Handle null weapon gracefully

                    var propInfo = weapon.GetType().GetProperty(_sortByText);
                    if (propInfo == null) return false; // Handle property not found

                    var weaponValue = propInfo.GetValue(weapon);
                    if (weaponValue == null)
                        return false;

                    int value;
                    if (!int.TryParse(weaponValue?.ToString(), out value))
                        return false;
                    return (value > 0);
                };
            }
            else if (_equipmentType.StartsWith("Horse"))
            {
                keySelector = p =>
                {
                    var horse = p.HorseComponent; // Use FirstOrDefault for safety
                    if (horse == null) return null; // Handle null weapon gracefully

                    var propInfo = horse.GetType().GetProperty(_sortByText);
                    if (propInfo == null) return null; // Handle property not found

                    return propInfo.GetValue(horse);
                };
                filterNull = p =>
                {
                    var horse = p.HorseComponent; // Use FirstOrDefault for safety
                    if (horse == null) return false; // Handle null weapon gracefully

                    var propInfo = horse.GetType().GetProperty(_sortByText);
                    if (propInfo == null) return false; // Handle property not found

                    return (propInfo.GetValue(horse) != null);
                };
            }
            else if (_isArmor)
            {
                keySelector = p =>
                {
                    var armor = p.ArmorComponent; // Use FirstOrDefault for safety
                    if (armor == null) return null; // Handle null weapon gracefully

                    var propInfo = armor.GetType().GetProperty(_sortByText);
                    if (propInfo == null) return null; // Handle property not found

                    return propInfo.GetValue(armor);
                };

                filterNull = p =>
                {
                    var armor = p.ArmorComponent; // Use FirstOrDefault for safety
                    if (armor == null) return false; // Handle null weapon gracefully

                    var propInfo = armor.GetType().GetProperty(_sortByText);
                    if (propInfo == null) return false; // Handle property not found

                    var armorValue = propInfo.GetValue(armor);
                    if (armorValue == null)
                        return false;

                    int value;
                    if (!int.TryParse(armorValue?.ToString(), out value))
                        return false;
                    else if (!string.IsNullOrEmpty(armorValue?.ToString()))
                    {
                        return true;
                    }

                    return (value > 0);
                };

            }
            // The existing reflection logic for when _sortByText is valid
            if (!_showEmpty)
            {
                localList = localList.Where(filterNull).ToList();
            }

            if (_ascending && (keySelector != null))
            {
                localList = localList.OrderBy(keySelector).ToList();
            }
            else
            {
                localList = localList.OrderByDescending(keySelector).ToList();
            }
        }*/
        return localList;
    }

    public List<ItemObject> GetFilteredList(List<ItemObject> currentList)
    {

        //List<ItemObject> localList = currentList;
        List<ItemObject> filteredList = new List<ItemObject>();
        /*foreach (ItemObject objectType in localList)
        {
            if (CustomUnitsBehavior.MatchesFilter(objectType, base.FilterTiers, base.FilterCulture, base.FilterWeaponTypes, _filter_armour_types))
            {
                filteredList.Add(objectType);
            }
        }*/
        return filteredList;
    }

    public override void RefreshData()
    {
        this.RefreshDataView();
    }

    public override void RefreshValues()
    {
        base.RefreshValues();
    }

    private void RefreshDataView()
    {
        this.Rows.Clear();
       
        //if (isFilterEnabled())
        //{
        //    localList = GetFilteredList(localList);
        //}
        // localList = GetSortedList(localList);

        // Use a local variable to manage the cards for the current row being built
        foreach(SettlementReligion manager in _settlementReligion.SettlementReligions.Values) { 
            Rows.Add(new SettlementReligionSectionVM(manager));
        }
        // Add initial empty card
        /*currentRow.AddCard(null, _troop, _equipmentType);

        foreach (ItemObject item in localList)
        {
            currentRow.AddCard(item, _troop, _equipmentType);

            // If we hit 5 items, we finalize the row and start a new list
            if (currentRow.Cards.Count == 5)
            {
                // Add the finalized row to the main Rows list
                Rows.Add(currentRow);

                // Start a new, empty list for the next row
                currentRow = new EquipmentCardRowVM();
            }
        }

        // Add any remaining cards as a final (potentially incomplete) row
        if (currentRow.Cards.Count > 0)
        {
            Rows.Add(currentRow);
        }*/
        this.RefreshValues();
    }


    public void EquipmentViewFilter()
    {
        this.RefreshValues();
    }

    public void Close()
    {
        _onComplete.Invoke();
    }
}