using Religions.ViewModel;

using SandBox.GauntletUI.AutoGenerated0;
using SandBox.View.Map;
using System.Threading;

using TaleWorlds.CampaignSystem;
using TaleWorlds.Engine.GauntletUI;
using TaleWorlds.InputSystem;
using TaleWorlds.MountAndBlade.GauntletUI;
using TaleWorlds.ScreenSystem;

namespace Religions.GauntletInterfaces
{
    internal sealed class RebelFactionsInterface : GenericInterface
    {
        protected override string MovieName => "RebelFactions";
        private bool _isEncyclopediaOpen = false;
        public void ShowInterface(ScreenBase screenBase, Kingdom kingdom)
        {
            if (!ShowInterfaceWithCheck())
                return;

            _screenBase = screenBase;

            var spriteData = UIResourceManager.SpriteData;
            var resourceContext = UIResourceManager.ResourceContext;
            var resourceDepot = UIResourceManager.ResourceDepot;
            spriteData.SpriteCategories["ui_encyclopedia"].Load(resourceContext, resourceDepot);
            spriteData.SpriteCategories["ui_kingdom"].Load(resourceContext, resourceDepot);
            
            //new TaleWorlds.Engine.GauntletUI.GauntletLayer("UI_MenuBackground", 0, false).LoadMovie("MenuBackground", null);
            _layer = new GauntletLayer("RebelFactions",221,false);
            _layer.InputRestrictions.SetInputRestrictions();
            _layer.Input.RegisterHotKeyCategory(HotKeyManager.GetCategory("GenericCampaignPanelsGameKeyCategory"));
            
            _isEncyclopediaOpen = false;
            if (((MapScreen) ScreenManager.TopScreen).EncyclopediaScreenManager.IsEncyclopediaOpen)
                _isEncyclopediaOpen = true;
                ((MapScreen) ScreenManager.TopScreen).EncyclopediaScreenManager.CloseEncyclopedia();
            
            ScreenManager.TopScreen.AddLayer(_layer);
            
            _layer.IsFocusLayer = true;
                    
            ScreenManager.TrySetFocus(_layer);

            screenBase.UpdateLayout();

            _vm = new RebelFactionsVM(kingdom, OnFinalize);

            _movie = _layer.LoadMovie(MovieName, _vm);

            //_movie = LoadMovie();
        }

        protected override void OnFinalize()
        {
            base.OnFinalize();
            if (_isEncyclopediaOpen)
            {
                ((MapScreen) ScreenManager.TopScreen).OpenEncyclopedia();
            }
        }
    }
}