using Diplomacy.Religions.ViewModel;
using Diplomacy.ViewModel;

using SandBox.GauntletUI.AutoGenerated0;
using SandBox.View.Map;

using System.Threading;

using TaleWorlds.CampaignSystem;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Engine.GauntletUI;
using TaleWorlds.InputSystem;
using TaleWorlds.MountAndBlade.GauntletUI;
using TaleWorlds.ScreenSystem;


namespace Diplomacy.GauntletInterfaces
{
    internal sealed class SettlementReligionInterface : GenericInterface
    {
        protected override string MovieName => "SettlementReligion";
        private bool _isEncyclopediaOpen = false;
        public void ShowInterface(ScreenBase screenBase, Settlement settlement)
        {
            if (!ShowInterfaceWithCheck())
                return;

            _screenBase = screenBase;

            var spriteData = UIResourceManager.SpriteData;
            var resourceContext = UIResourceManager.ResourceContext;
            var resourceDepot = UIResourceManager.ResourceDepot;
            spriteData.SpriteCategories["ui_encyclopedia"].Load(resourceContext, resourceDepot);
            spriteData.SpriteCategories["ui_kingdom"].Load(resourceContext, resourceDepot);
            
            _layer = new GauntletLayer("SettlementReligion",221,false);
            _layer.InputRestrictions.SetInputRestrictions();
            _layer.Input.RegisterHotKeyCategory(HotKeyManager.GetCategory("GenericCampaignPanelsGameKeyCategory"));

            _isEncyclopediaOpen = false;
            
            ScreenManager.TopScreen.AddLayer(_layer);
            
            _layer.IsFocusLayer = true;
                    
            ScreenManager.TrySetFocus(_layer);

            screenBase.UpdateLayout();

            _vm = new SettlementReligionVM(settlement, OnFinalize);

            _movie = _layer.LoadMovie(MovieName, _vm);

            //_movie = LoadMovie();
        }

        protected override void OnFinalize()
        {
            base.OnFinalize();
            if (_isEncyclopediaOpen)
            {
                ((MapScreen) ScreenManager.TopScreen).OpenEncyclopedia();
            }
        }
    }
}