using StoryMode.GauntletUI.AutoGenerated;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Policy;
using System.Text;
using System.Threading.Tasks;

using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.MountAndBlade.GauntletUI.AutoGenerated0;

namespace Diplomacy.Religions
{
    public class SettlementReligionContainer
    {
        public Dictionary<string, double> ReligionPopulationCount { get; private set; }

        public Dictionary<string, SettlementReligion> SettlementReligions { get; private set; } = new Dictionary<string, SettlementReligion>();
        public Settlement Settlement { get; private set; }
        public SettlementReligionContainer(Settlement settlement)
        {
            Settlement = settlement;
            if (SettlementReligions.IsEmpty())
            {

            }
        }

        public void SettlementReligionFactory()
        {
            var culture = Settlement.Culture;
            double populationTotal = 1;
            double dice = 0.0;
            var populationTotalMod = ReligionFactory.ReligionFactoryData[culture.StringId].Values.Sum(x => x);


            foreach (var religion in ReligionFactory.ReligionFactoryData[culture.StringId].Keys)
            {
                dice = (ReligionFactory.ReligionFactoryData[culture.StringId][religion] / populationTotal) + ((0.5 - new Random().NextDouble()) * 0.1);
                if (populationTotal > 0)
                {
                    if (dice < populationTotalMod)
                    {
                        ReligionPopulationCount.Add(religion, dice);
                        populationTotal = populationTotal - dice;
                    }
                    else
                    {
                        ReligionPopulationCount.Add(religion, populationTotalMod);
                    }
                    SettlementReligions.Add(religion, new SettlementReligion(religion, this));
                }

            }
        }

        public void CaluculateCurrentConversionRate()
        {
            Dictionary<string, double> rates = new Dictionary<string, double>();

            double conversionScore = 0.0;
            List<double> ConversionMatrix = new List<double>();
            List<double> ConversionRow;

            foreach (var religionX in SettlementReligions)
            {
                ConversionRow = new List<double>();
                //Calculations.Add((0.0 + religionX.Value.GetCurrentConversionScore()));
                foreach (var religionY in SettlementReligions)
                {
                    conversionScore += SettlementReligions[religionY.Key].GetCurrentConversionScore();
                }

            }
        }





        public class SettlementReligion
        {
            public string ReligionId { get; private set; }
            public int? CurrentConversionRate { get; set; }

            public ReligiousBuildingLevel Temple { get; private set; } = ReligiousBuildingLevel.None;
            public ReligiousBuildingLevel Monument { get; private set; } = ReligiousBuildingLevel.None;
            public ReligiousBuildingLevel Monastary { get; private set; } = ReligiousBuildingLevel.None;
            public int TempleBuildResources { get; private set; } = 0;
            public int MonumentBuildResources { get; private set; } = 0;
            public int MonastaryBuildResources { get; private set; } = 0;

            public SettlementReligionContainer ParentSettlementReligion { get; private set; }
            public SettlementReligion(string religionId, SettlementReligionContainer parent)
            {
                ParentSettlementReligion = parent;
                ReligionId = religionId;
            }

            public int GetCurrentConversionScore()
            {
                int ConversionRate = 0;
                
                Religion baseReligion = ReligionManager.GetReligion(this.ReligionId);
                //Set the initial value as the base conversion rate
                ConversionRate = baseReligion.Stats.Conversion;

                //Add building bonuses
                ConversionRate += ((int) Temple) * 3;

                //Add governor bonus
                ConversionRate += (this.ParentSettlementReligion.Settlement.Owner)

                //Add city owner bonus

                return ConversionRate;
            }


        }


    }
}
