using Religions.Religion.Extensions;

using StoryMode.GauntletUI.AutoGenerated;

using System;
using System.Collections.Generic;
using System.Data.SqlTypes;
using System.Linq;
using System.Security.Policy;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.MountAndBlade;
using TaleWorlds.MountAndBlade.GauntletUI.AutoGenerated0;
using TaleWorlds.SaveSystem;

namespace Religions.Religion
{
    //[SaveableRootClass(527006)]
   

    public enum ReligiousBuildingLevel
    {
        None,
        Level1,
        Level2,
        Level3
    }

    public enum ReligionBuildingType
    {
        Temple,
        Monument,
        Monastary
    }

    public enum TempleResourceLevels
    {
        Level0 = 0,
        Level1 = 50000,
        Level2 = 500000, 
        Level3 = 1200000
    }

    public class SettlementReligion
    {
        [SaveableProperty(1)]
        public string ReligionId { get; private set; }
        [SaveableProperty(2)]
        public int CurrentConversionRate { get; set; }
        [SaveableProperty(3)]
        public ReligiousBuildingLevel Temple { get; private set; } = ReligiousBuildingLevel.None;
        [SaveableProperty(4)]
        public ReligiousBuildingLevel Monument { get; private set; } = ReligiousBuildingLevel.None;
        [SaveableProperty(5)]
        public ReligiousBuildingLevel Monastary { get; private set; } = ReligiousBuildingLevel.None;
        [SaveableProperty(6)]
        public int TempleBuildResources { get; private set; } = 0;
        [SaveableProperty(7)]
        public int MonumentBuildResources { get; private set; } = 0;
        [SaveableProperty(8)]
        public int MonastaryBuildResources { get; private set; } = 0;
        [SaveableProperty(9)]
        public int Zeal {  get; private set; } = 0;
        [SaveableProperty(10)]
        public int Unrest {  get; private set; } = 0;
        [SaveableProperty(11)]
        public string SettlmentId { get; private set; }
        [SaveableProperty(12)]
        public int ImmigrationScore
        {
            get
            {
                if(ImmigrationMap == null)
                    return 0;
                return ImmigrationMap.Count;
            }
            set
            {
                // ImmigrationScore is calculated based on the ImmigrationMap count
            }
        }

        [SaveableProperty(13)]
        public List<string> ImmigrationMap { get; private set; }
        public SettlementReligion(string religionId, SettlementReligionContainer parent)
        {
            SettlmentId = parent.Settlement.StringId;
            ReligionId = religionId;
            CurrentConversionRate = 0;
            ImmigrationMap = new List<string>();
        }

        public SettlementReligion(string religionId, string settlementId)
        {
            
            ReligionId = religionId;
            CurrentConversionRate = 0;
        }

        public void SetImmigrationMap(List<string> map)
        {
            ImmigrationMap = map;
        }

        public SettlementReligionContainer GetParent()
        {
            return ReligionManager.GetSettlementContainer(SettlmentId);
        }

        public int GetBuildingConversionBonus()
        {
            int ConversionRate = 0;
            ConversionRate += ((int) Temple) * 3;
            return ConversionRate;
        }

        public int GetCurrentConversionScore()
        {
            int ConversionRate = 0;
                
            Religion baseReligion = ReligionManager.GetReligion(this.ReligionId);
            //Set the initial value as the base conversion rate
            ConversionRate = baseReligion.Tier;

            //Add building bonuses
            ConversionRate += GetBuildingConversionBonus();

            //Settlement owner bonus
            if (hasOwnerBonus())
            {
                ConversionRate += 2;
            }

            //Settlement governer bonus
            if(hasGovernorBonus())
            {
                ConversionRate += 1;
            }

            ConversionRate += ImmigrationScore;
            this.CurrentConversionRate = ConversionRate;
            return ConversionRate;
        }

        public bool hasGovernorBonus()
        {
            var Parent = GetParent();
            var governor = Parent.Settlement.Town?.Governor;
            var owner = Parent.Settlement.Owner;
            if (governor == owner)
                return false;
            var govReligion = governor?.GetHeroReligion();
            if (govReligion != null && govReligion.ReligionId == this.ReligionId)
            {
                return true;
            }
            return false;
        }

        public bool hasOwnerBonus()
        {
            var Parent = GetParent();
            var owner = Parent.Settlement.Owner;
            var ownerReligion = owner?.GetHeroReligion();
            if (ownerReligion != null && ownerReligion.ReligionId == this.ReligionId)
            {
                return true;
            }
            return false;
        }

        public void AddBuildingResources(int resources)
        {
            TempleBuildResources += resources;
            MonumentBuildResources += resources;
            if (TempleBuildResources >= (int)TempleResourceLevels.Level3)
            {
                Temple = ReligiousBuildingLevel.Level3;
            }
            else if (TempleBuildResources >= (int)TempleResourceLevels.Level2)
            {
                Temple = ReligiousBuildingLevel.Level2;
            }
            else if (TempleBuildResources >= (int)TempleResourceLevels.Level1)
            {
                Temple = ReligiousBuildingLevel.Level1;
            }
        }

        public void AddBuilding(ReligionBuildingType buildingType, ReligiousBuildingLevel buildingLevel)
        {
            switch (buildingType)
            {
                case ReligionBuildingType.Temple:
                    Temple = buildingLevel;
                    break;
                case ReligionBuildingType.Monument:
                    Monument = buildingLevel;
                    break;
                case ReligionBuildingType.Monastary:
                    Monastary = buildingLevel;
                    break;
            }
        }
    }
}
